// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/bryansandoval/projects/counter/src/Services/input_service.go

// Package Services_mocks is a generated GoMock package.
package Services_mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockInputService is a mock of InputService interface
type MockInputService struct {
	ctrl     *gomock.Controller
	recorder *MockInputServiceMockRecorder
}

// MockInputServiceMockRecorder is the mock recorder for MockInputService
type MockInputServiceMockRecorder struct {
	mock *MockInputService
}

// NewMockInputService creates a new mock instance
func NewMockInputService(ctrl *gomock.Controller) *MockInputService {
	mock := &MockInputService{ctrl: ctrl}
	mock.recorder = &MockInputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInputService) EXPECT() *MockInputServiceMockRecorder {
	return m.recorder
}
